#!/usr/bin/env node
// scripts/gen-agents.mjs - generates AGENTS.md from lib/playbooks.mjs (the single
// per-platform prose source). The per-platform sections are DERIVED, never
// hand-edited; the hand-authored contract lives in PREAMBLE below. A freshness
// test (test/agents-md-freshness.test.mjs) fails `npm run check` if AGENTS.md
// drifts from this generator - regenerate with `node scripts/gen-agents.mjs --write`.
//
// Reads PLAYBOOKS only (no setup.mjs / setupStatus state) so the output is a pure
// function of a frozen const - deterministic across machines and CI.
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { PLAYBOOKS, RADAR_SOURCE_PLAYBOOKS } from '../lib/playbooks.mjs';

// Platform order + short display names. The keys ARE the single source; these
// labels are local doc presentation (headings), not business logic.
const ORDER = [
  'meta', 'linkedin', 'x', 'youtube', 'telegram', 'discord', 'reddit',
  'pinterest', 'tiktok', 'mastodon', 'wordpress', 'ghost', 'nostr', 'gbp',
];
// Radar (beta) SEARCH sources (spec 33): listening sources, NOT publish/setup lanes, so
// they come from RADAR_SOURCE_PLAYBOOKS (separate from the key-parity-locked PLAYBOOKS)
// and render as their own section below the publish platforms. Reddit search uses the
// SAME script app as Reddit publishing (documented as a step in its platform section),
// so it is not repeated here - only the search-only sources are.
const RADAR_ORDER = ['bluesky', 'hackernews'];
const RADAR_DISPLAY = { bluesky: 'Bluesky', hackernews: 'Hacker News' };
const DISPLAY = {
  meta: 'Meta (Instagram + Facebook)',
  linkedin: 'LinkedIn',
  x: 'X',
  youtube: 'YouTube',
  telegram: 'Telegram',
  discord: 'Discord',
  reddit: 'Reddit (beta)',
  pinterest: 'Pinterest (beta)',
  tiktok: 'TikTok (beta)',
  mastodon: 'Mastodon',
  wordpress: 'WordPress',
  ghost: 'Ghost',
  nostr: 'Nostr',
  gbp: 'Google Business Profile (beta)',
};

const HEADER =
  '<!-- DO NOT EDIT. Generated by scripts/gen-agents.mjs from lib/playbooks.mjs ' +
  '(the per-platform sections). Run `node scripts/gen-agents.mjs --write` after ' +
  'editing playbooks. The contract preamble is authored in that script. -->';

const PREAMBLE = `# AGENTS.md

pendpost is a local-first, MCP-native social planner with a human approval gate.
An agent drafts, schedules, and (once trusted) publishes across Instagram,
Facebook, LinkedIn, X, YouTube, Telegram, Discord, Reddit, Pinterest, TikTok,
Mastodon, WordPress, Ghost, Nostr, and Google Business Profile; a human approves
before anything goes out. Reddit, Pinterest, TikTok, and Google Business Profile
are beta lanes (each gated by a vendor trial/audit/access step, called out in its
playbook below).
This file is the contract for an AI agent operating pendpost. The per-platform
sections at the end are generated from lib/playbooks.mjs.

## Mock-first

With no credentials, pendpost runs the full draft -> approve -> schedule ->
publish -> insights loop in mock mode (no network; nothing leaves the machine).
Exercise everything here before connecting a real platform.

## Connecting as an agent

- One-click: install the Claude Desktop \`.mcpb\` bundle - it self-boots
  \`npx -y pendpost --stdio\`, so there is no separate server to start.
- Or run \`npx -y pendpost --stdio\` and point any stdio MCP client at it.
- Dev / Claude Code over HTTP (the server must already be running via
  \`npx pendpost\`): \`claude mcp add --transport http pendpost http://127.0.0.1:8090/mcp\`.

## The approval gate (non-negotiable)

- Every post carries an approval state; a missing or \`draft\` state means it will
  NOT publish.
- An actor can never approve its own post (no self-approval): the actor passed to
  \`plan_create_post\` cannot later \`approve_post\` it. Only \`actor:"owner"\` is exempt,
  as the approval authority; an agent approves ONLY on the owner's explicit
  instruction. \`plan_update_post\` can never touch approval.
- Auto-approve (the progressive-autonomy policy) is OWNER-ONLY: only \`actor:"owner"\`
  can enable it via \`config_set\` \`set.posting.autoApprove\` - an agent can never turn
  it on for itself. When enabled it approves under a distinct policy actor, never the
  post's creator, so the no-self-approval rule still holds. Its platforms scope is
  fail-closed: an empty \`platforms\` list approves NOTHING (the owner must trust at
  least one platform), while empty \`campaigns\`/\`types\` lists mean no constraint on
  that axis.
- \`publish_due_run\` does REAL publishes and needs \`confirm:true\` - never call it
  unless the owner asks.

## Secrets never flow through you

You NEVER read, type, paste, or write a raw secret or token. \`config_set\` can
set non-secret identifiers only, never a secret. Secrets are entered ONLY by the
owner, in a local ceremony the owner runs themselves - the per-engine CLI or the
dashboard Setup page - which writes \`.env\` at mode 0600; the token never passes
through the agent or the chat.

## Per-platform setup loop

For each platform that is not validated-live or skipped:

1. Call \`pendpost_health\` and read \`setup.<platform>\` -
   \`{ status, validation, missing[], connectAction, playbook }\`.
2. Open \`playbook.portalUrl\`, create the app, add the products, request the
   scopes, and work \`playbook.steps\` in order. For each step, name the exact env
   var / identifier it sets (\`step.env\` / \`step.field\`).
3. A missing IDENTIFIER (\`kind:"identifier"\`): ask the owner and write it with
   \`config_set\` (\`set.identifiers\`). A missing SECRET (\`kind:"secret"\`): give the
   owner the exact CLI to run (the step's \`cli\` / the \`connectAction\`); the owner
   runs it and the localhost callback writes \`.env\`.
4. Call \`health_recheck{platform}\` to VALIDATE - a read-only liveness probe that
   surfaces the REAL pass/fail (\`validation.ok\` + \`.detail\`). On failure, relay
   \`validation.fix\` and re-probe.

\`setup.ready\` is true ONLY when every platform is validated-live (a passing probe)
or explicitly skipped - a connected-but-unproven lane is NOT ready. The dashboard
Setup page reads the same \`setup\` field.

## The per-platform playbooks

The sections below are generated from lib/playbooks.mjs (the single prose source).
They are what a cold agent needs to drive each developer portal; at runtime the
same data arrives live (with per-lane status) via \`pendpost_health\`'s
\`setup.<platform>.playbook\`.`;

function renderSteps(steps = []) {
  return steps
    .map((s, i) => {
      let line = `${i + 1}. **${s.title}** - ${s.detail}`;
      const tags = [];
      if (s.env) tags.push(`sets env \`${s.env}\``);
      if (s.field) tags.push(`sets identifier \`${s.field}\``);
      if (tags.length) line += ` _(${tags.join('; ')})_`;
      if (s.cli) line += `\n   \`\`\`bash\n   ${s.cli}\n   \`\`\``;
      return line;
    })
    .join('\n');
}

function renderPlatform(key) {
  const pb = PLAYBOOKS[key];
  const failures = (pb.commonFailures || [])
    .map((f) => `- _${f.symptom}_ ${f.cause} **Fix:** ${f.fix}`)
    .join('\n');
  return [
    `## ${DISPLAY[key]}`,
    '',
    `- **Portal:** ${pb.portalUrl}`,
    `- **App to create:** ${pb.appToCreate}`,
    `- **Products to add:** ${(pb.productsToAdd || []).join(', ')}`,
    `- **Scopes to request:** \`${(pb.scopes || []).join(' ')}\``,
    '',
    '**Steps**',
    '',
    renderSteps(pb.steps),
    '',
    '**Common failures**',
    '',
    failures,
  ].join('\n');
}

// A Radar (beta) SEARCH source (spec 33). Simpler than a publish playbook: no
// products/scopes, just the BYO-credential steps + common failures. bluesky/hacker-news.
function renderRadarSource(key) {
  const pb = RADAR_SOURCE_PLAYBOOKS[key];
  const failures = (pb.commonFailures || [])
    .map((f) => `- _${f.symptom}_ ${f.cause} **Fix:** ${f.fix}`)
    .join('\n');
  return [
    `### ${RADAR_DISPLAY[key]}`,
    '',
    `- **Portal:** ${pb.portalUrl}`,
    `- **What to create:** ${pb.appToCreate}`,
    '',
    '**Steps**',
    '',
    renderSteps(pb.steps),
    '',
    '**Common failures**',
    '',
    failures,
  ].join('\n');
}

export function render() {
  const sections = ORDER.map(renderPlatform).join('\n\n');
  const radar = [
    '## Radar (beta) sources',
    '',
    'Radar (beta) is opt-in, default-off social listening (`posting.radar.enabled`). It searches '
    + 'these sources for your saved buyer-intent queries and ranks hits by intent - it never publishes. '
    + 'Reddit search reuses the SAME script app as Reddit publishing (see the Reddit section above). '
    + 'Bluesky and Hacker News are search-ONLY sources (never publish targets):',
    '',
    RADAR_ORDER.map(renderRadarSource).join('\n\n'),
  ].join('\n');
  return `${HEADER}\n\n${PREAMBLE}\n\n${sections}\n\n${radar}\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const out = render();
  if (process.argv.includes('--write')) {
    fs.writeFileSync(new URL('../AGENTS.md', import.meta.url), out);
    console.log('wrote AGENTS.md');
  } else {
    process.stdout.write(out);
  }
}
