#!/usr/bin/env node
// scripts/gen-agents.mjs - generates AGENTS.md from lib/playbooks.mjs (the single
// per-platform prose source). The per-platform sections are DERIVED, never
// hand-edited; the hand-authored contract lives in PREAMBLE below. A freshness
// test (test/agents-md-freshness.test.mjs) fails `npm run check` if AGENTS.md
// drifts from this generator - regenerate with `node scripts/gen-agents.mjs --write`.
//
// Reads PLAYBOOKS only (no setup.mjs / setupStatus state) so the output is a pure
// function of a frozen const - deterministic across machines and CI.
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
import { PLAYBOOKS } from '../lib/playbooks.mjs';

// Platform order + short display names. The keys ARE the single source; these
// labels are local doc presentation (headings), not business logic.
const ORDER = ['meta', 'linkedin', 'x', 'youtube'];
const DISPLAY = {
  meta: 'Meta (Instagram + Facebook)',
  linkedin: 'LinkedIn',
  x: 'X',
  youtube: 'YouTube',
};

const HEADER =
  '<!-- DO NOT EDIT. Generated by scripts/gen-agents.mjs from lib/playbooks.mjs ' +
  '(the per-platform sections). Run `node scripts/gen-agents.mjs --write` after ' +
  'editing playbooks. The contract preamble is authored in that script. -->';

const PREAMBLE = `# AGENTS.md

pendpost is a local-first, MCP-native social planner with a human approval gate.
An agent drafts, schedules, and (once trusted) publishes across Facebook,
Instagram, LinkedIn, YouTube, and X; a human approves before anything goes out.
This file is the contract for an AI agent operating pendpost. The per-platform
sections at the end are generated from lib/playbooks.mjs.

## Mock-first

With no credentials, pendpost runs the full draft -> approve -> schedule ->
publish -> insights loop in mock mode (no network; nothing leaves the machine).
Exercise everything here before connecting a real platform.

## Connecting as an agent

- One-click: install the Claude Desktop \`.mcpb\` bundle - it self-boots
  \`npx -y pendpost --stdio\`, so there is no separate server to start.
- Or run \`npx -y pendpost --stdio\` and point any stdio MCP client at it.
- Dev / Claude Code over HTTP (the server must already be running via
  \`npx pendpost\`): \`claude mcp add --transport http pendpost http://127.0.0.1:8090/mcp\`.

## The approval gate (non-negotiable)

- Every post carries an approval state; a missing or \`draft\` state means it will
  NOT publish.
- An actor can never approve its own post (no self-approval). Approval authority
  is the owner (\`actor:"owner"\`); an agent approves ONLY on the owner's explicit
  instruction.
- \`publish_due_run\` does REAL publishes and needs \`confirm:true\` - never call it
  unless the owner asks.

## Secrets never flow through you

You NEVER read, type, paste, or write a raw secret or token. \`config_set\` can
set non-secret identifiers only, never a secret. Secrets are minted ONLY by the
per-engine CLI ceremony the owner runs locally (it writes \`.env\` at mode 0600);
the token never passes through the agent, the chat, or the dashboard.

## Per-platform setup loop

For each platform that is not validated-live or skipped:

1. Call \`pendpost_health\` and read \`setup.<platform>\` -
   \`{ status, validation, missing[], connectAction, playbook }\`.
2. Open \`playbook.portalUrl\`, create the app, add the products, request the
   scopes, and work \`playbook.steps\` in order. For each step, name the exact env
   var / identifier it sets (\`step.env\` / \`step.field\`).
3. A missing IDENTIFIER (\`kind:"identifier"\`): ask the owner and write it with
   \`config_set\` (\`set.identifiers\`). A missing SECRET (\`kind:"secret"\`): give the
   owner the exact CLI to run (the step's \`cli\` / the \`connectAction\`); the owner
   runs it and the localhost callback writes \`.env\`.
4. Call \`health_recheck{platform}\` to VALIDATE - a read-only liveness probe that
   surfaces the REAL pass/fail (\`validation.ok\` + \`.detail\`). On failure, relay
   \`validation.fix\` and re-probe.

\`setup.ready\` is true ONLY when every platform is validated-live (a passing probe)
or explicitly skipped - a connected-but-unproven lane is NOT ready. The dashboard
Setup page reads the same \`setup\` field.

## The per-platform playbooks

The sections below are generated from lib/playbooks.mjs (the single prose source).
They are what a cold agent needs to drive each developer portal; at runtime the
same data arrives live (with per-lane status) via \`pendpost_health\`'s
\`setup.<platform>.playbook\`.`;

function renderSteps(steps = []) {
  return steps
    .map((s, i) => {
      let line = `${i + 1}. **${s.title}** - ${s.detail}`;
      const tags = [];
      if (s.env) tags.push(`sets env \`${s.env}\``);
      if (s.field) tags.push(`sets identifier \`${s.field}\``);
      if (tags.length) line += ` _(${tags.join('; ')})_`;
      if (s.cli) line += `\n   \`\`\`bash\n   ${s.cli}\n   \`\`\``;
      return line;
    })
    .join('\n');
}

function renderPlatform(key) {
  const pb = PLAYBOOKS[key];
  const failures = (pb.commonFailures || [])
    .map((f) => `- _${f.symptom}_ ${f.cause} **Fix:** ${f.fix}`)
    .join('\n');
  return [
    `## ${DISPLAY[key]}`,
    '',
    `- **Portal:** ${pb.portalUrl}`,
    `- **App to create:** ${pb.appToCreate}`,
    `- **Products to add:** ${(pb.productsToAdd || []).join(', ')}`,
    `- **Scopes to request:** \`${(pb.scopes || []).join(' ')}\``,
    '',
    '**Steps**',
    '',
    renderSteps(pb.steps),
    '',
    '**Common failures**',
    '',
    failures,
  ].join('\n');
}

export function render() {
  const sections = ORDER.map(renderPlatform).join('\n\n');
  return `${HEADER}\n\n${PREAMBLE}\n\n${sections}\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const out = render();
  if (process.argv.includes('--write')) {
    fs.writeFileSync(new URL('../AGENTS.md', import.meta.url), out);
    console.log('wrote AGENTS.md');
  } else {
    process.stdout.write(out);
  }
}
